### PR TITLE
Implement #31: Drag and drop between boards

### PR DESCRIPTION
**Pull request by pjeby**
Cards and lanes can be dragged between board views.  (Note that dragging between boards can break links, depending on your Obsidian link settings and whether you have notes with the same name in different locations.)

This is a significant re-organization and should probably be tested more thoroughly, as I only use a fraction of the plugin's features and might not notice if I broke something.

### CODE REVIEW

**Comment by pjeby** [comment]
So, one thing this PR doesn't do yet is update an item's completion status when you drag it to a different board.  I was going over the following logic in the existing moveItem, and ran into a bit of a snag:

https://github.com/mgmeyers/obsidian-kanban/blob/93005bbfb50937dc21eb528d06e5b669b74e11c2/src/components/helpers.ts#L86-L90

This first part seems reasonable enough; "should complete" for the lane, "is complete" for the item state.  So far so good.  But now we're setting isComplete in two possible branches of this if, with a third (unwritten) branch leaving it alone if -- and *only* if -- both the old lane *and* the new lane are *not* set to mark complete (why?):

https://github.com/mgmeyers/obsidian-kanban/blob/93005bbfb50937dc21eb528d06e5b669b74e11c2/src/components/helpers.ts#L100-L107

Next, it gets a bit more confusing: we ignore everything we just did and straight-up compare "should complete" with the original "is complete", but then set the value using the tri-state value (true, false, or unchanged) we just computed:

https://github.com/mgmeyers/obsidian-kanban/blob/93005bbfb50937dc21eb528d06e5b669b74e11c2/src/components/helpers.ts#L109-L113

If I try to translate all the above into English, it seems like the resulting logic is, "if the completion states of the lane and item are different, update the item completion to match...  *unless* both columns were non-check columns, in which case leave its state alone."  Which actually makes sense, I suppose, but I wanted to verify.  Because it seems to me that if that's the intent, it could be rendered as, e.g.

```ts
const newLaneCompletesItems = lanes[destinationLaneIndex].data.shouldMarkItemsComplete;
const oldLaneCompletesItems = lanes[sourceLaneIndex].data.shouldMarkItemsComplete;

if (newLaneCompletesItems || oldLaneCompletesItems) {
  if (newLaneCompletesItems != !!item.data.isComplete) {
    item = update(item, {data: {isComplete: {$set: newLaneCompletesItems}}});
  }
}
```

But apart from how the logic is rendered, there's a bigger question in my mind, which is why is this doing this?  The only difference between doing this and just "make the item match the lane" is for the case where neither lane marks things completed, and the item is complete.  (If the item is incomplete, there would be no change in behavior.)

Specifically, I'm wondering, "How do you ever get in a state where the item is complete, but in a column where you don't mark things complete?"  You would have to either change the lane state or manually edit the file, since if you were moving items between columns without such changes, there's no way for this logic to get an item *into* a completed state while in a not-completing column.  Or am I missing something here?

**Comment by mgmeyers** [comment]
> Specifically, I'm wondering, "How do you ever get in a state where the item is complete, but in a column where you don't mark things complete?" You would have to either change the lane state or manually edit the file, since if you were moving items between columns without such changes, there's no way for this logic to get an item _into_ a completed state while in a not-completing column. Or am I missing something here?

@pjeby So one thing to note is that there's a setting to show checkboxes for each card:

Screen Shot 2021-06-04 at 3 20 24 PM

Let me see if I can remember my logic here....

```typescript
// If the card is moving into a lane where shouldMarkItemsComplete is true
// mark it as complete
if (shouldMarkAsComplete) {
  isComplete = true;

// Else, if the card is moving out of a "complete" lane into a "not-complete" lane
// mark it as incomplete
} else if (
  !shouldMarkAsComplete &&
  !!lanes[sourceLaneIndex].data.shouldMarkItemsComplete
) {
  isComplete = false;
}

// This is where things are a little off, this should really be: 
//    "only update the item if something has changed"
// So... isComplete !== item.data.isComplete
if (shouldMarkAsComplete !== item.data.isComplete) {
  item = update(item, {
    data: {
      isComplete: {
        $set: isComplete,
      },
    },
  });
}
```

Does that clarify things?

**Comment by pjeby** [comment]
Bonus round!  I fixed those `Unable to find drag handle` warnings.  Apparently r-b-dnd uses querySelectorAll() to find drag handles, *but* by the time `onClose()` is called, the view's DOM is already unmounted.  Not sure why *unmounting* causes a problem at that point, but oh well.  The fix was easy, so I threw it in.  I'm going to try to stop working on this now.  :wink:

**Comment by mgmeyers** [comment]
> On an unrelated note, I figured out how to build this with esbuild and preact, which gets the file size down a bit and the build time down by a factor of 3-5x, while still pushing to a test vault for development. Obsidian reloads the plugin almost faster than I can switch windows away from VSCode now. 😁 Would you be interested in a PR for that?

Yeah, as long as everything still works, sounds great to me!

Thanks for all the work you put into this. These are some great improvements, and a really creative solution to the dragging between boards problem.

**Comment by mgmeyers** [comment]
Just tested everything out. This works so well! Thanks again

**Pull request merged**
